# general configuration
url: http://newcomers.co
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "https://unsplash.it/200/200?image=177"
  # author will appear under the avatar (optional)
  author: "Newcomers"
  # tagline will appear under the title (optional)
  tagline: "A podcast about our relationships with each other, cities, and nature."
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true
